# Runs unit tests.

name: unit

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: |
          cargo nextest run \
            --locked \
            --workspace \
            -E "(kind(lib) | kind(bin) | kind(proc-macro)) & !package(odyssey-e2e-tests)"

  doc:
    name: doc tests
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run doctests
        run: cargo test --doc --workspace

  unit-success:
    name: unit success
    runs-on: ubuntu-latest
    if: always()
    needs: [test]
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
